import type { NextPage } from 'next'
import Image from 'next/image'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import ResponsiveAppBar from "../components/navbar";
import Layout from "../components/Layout";
import Typography from "@mui/material/Typography";

const Home: NextPage = () => {
  return (
      <Layout>
          <div className={styles.container}>
              <Head>
                  <title>ECE 477 VRMS</title>
                  <meta name="description" content="Generated by create next app" />
                  <link rel="icon" href="/favicon.ico" />
              </Head>

              <div>
                  {/*<Image src={"/Files/img/BannerImgExample.jpg"} layout={'fill'}/>*/}
                  <Typography>Project Overview</Typography>
                  <Typography>
                      This is the place to talk about your project.
                      What problem does it address? How does/might it work?
                      How does it compare to competing methods and/or approaches to
                      solving the problem? Summarize your initial project proposal in 1-3 paragraphs and put that
                      information here.
                  </Typography>
                  <Typography>Project Specific Success Criteria:</Typography>
                  <ul>
                      <li>PSSC #1: An ability to....</li>
                      <li>PSSC #2: An ability to....</li>
                      <li>PSSC #3: An ability to....</li>
                      <li>PSSC #4: An ability to....</li>
                      <li>PSSC #5: An ability to....</li>
                  </ul>
              </div>
          </div>
      </Layout>
  )
}

export default Home
